hibernate.hbm2ddl.auto=create-drop
hibernate.show_sql=true

spring.application.name=selfbill-api
spring.main.allow-bean-definition-overriding=true

# SQLite
spring.datasource.url=jdbc:sqlite:./selfbill.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# JPA/Hibernate
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
    # Enable true for Debbugging SQL Queries
spring.jpa.show-sql=false

# Configuración de logs
logging.level.root=INFO
logging.level.com.luispuchol.selfbill=INFO
logging.level.org.springframework.web=INFO
    # Enable "DEBUG" for debugging Hibernate SQL generation
logging.level.org.hibernate=WARN

# SpringDoc/Swagger
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html